### ISSUE TITLE
unregisterReceiver for android.net.conn.CONNECTIVITY_CHANGE missing

### ISSUE THREAD

**Issue by mariannegru** [PayPal-Mobile/android-here-sdk-dist#54]
Hi,

Is there a way to solve this issue? I can not find any call on PayPalHereSDK to unregister

`03-28 08:42:42.535 17696-17696/com.icabbi.paypal E/ActivityThread: Activity com.icabbi.paypal.MainActivity has leaked IntentReceiver com.paypal.merchant.sdk.internal.NetworkConnectivityReceiver@4144a198 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                   android.app.IntentReceiverLeaked: Activity com.icabbi.paypal.MainActivity has leaked IntentReceiver com.paypal.merchant.sdk.internal.NetworkConnectivityReceiver@4144a198 that was originally registered here. Are you missing a call to unregisterReceiver()?
                                                                       at android.app.LoadedApk$ReceiverDispatcher.<init>(LoadedApk.java:795)
                                                                       at android.app.LoadedApk.getReceiverDispatcher(LoadedApk.java:596)
                                                                       at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1368)
                                                                       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1348)
                                                                       at android.app.ContextImpl.registerReceiver(ContextImpl.java:1342)
                                                                       at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:423)
                                                                       at com.paypal.merchant.sdk.internal.SDKCore.initNetworkConnectivityReceiver(SDKCore.java:219)
                                                                       at com.paypal.merchant.sdk.internal.SDKCore.init(SDKCore.java:163)
                                                                       at com.paypal.merchant.sdk.PayPalHereSDK.init(PayPalHereSDK.java:163)
                                                                       at com.icabbi.paypal.payment.PayPal.init(PayPal.java:38)
                                                                       at com.icabbi.common.payment.Payment.initialize(Payment.java:15)
                                                                       at com.icabbi.common.payment.models.ApplicationModel.initialize(ApplicationModel.java:54)
                                                                       at com.icabbi.paypal.models.StatusModel.initialize(StatusModel.java:31)
                                                                       at com.icabbi.paypal.models.StatusModel.access$000(StatusModel.java:13)
                                                                       at com.icabbi.paypal.models.StatusModel$1.run(StatusModel.java:22)
                                                                       at android.os.Handler.handleCallback(Handler.java:725)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                       at android.os.Looper.loop(Looper.java:137)
                                                                       at android.os.HandlerThread.run(HandlerThread.java:60)`

Thank you

**Comment by ppmtscory** [comment]
@mariannegru can you tell me how to reproduce this issue so that I can see what may be happening?

**Comment by mariannegru** [comment]
I've added a check for initialised and is fine now.
