### ISSUE TITLE
Payment issue

### ISSUE THREAD

**Issue by mariannegru** [PayPal-Mobile/android-here-sdk-dist#56]
Hi,

Using PayPalHereSDK.getTransactionManager().processPaymentWithSDKUI I receive this error:

`                                                                   java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.paypal.merchant.sdk.domain.Address.getLine1()' on a null object reference
                                                                       at com.paypal.merchant.sdk.internal.service.impl.hereapi.HereInvoiceCreateRequest.getPayloadAsString(HereInvoiceCreateRequest.java:84)
                                                                       at com.paypal.merchant.sdk.internal.service.impl.hereapi.HereInvoiceUpdateRequest.getPayloadAsString(HereInvoiceUpdateRequest.java:62)
                                                                       at com.paypal.merchant.sdk.internal.service.ServiceInterfaceVolleyImpl.submit(ServiceInterfaceVolleyImpl.java:209)
                                                                       at com.paypal.merchant.sdk.internal.service.InvoiceServiceImpl.updateInvoice(InvoiceServiceImpl.java:205)
                                                                       at com.paypal.merchant.sdk.internal.TransactionManagerImpl.processPaymentWithBackend(TransactionManagerImpl.java:944)
                                                                       at com.paypal.merchant.sdk.internal.TransactionManagerImpl.moveStateToProcessingPayment(TransactionManagerImpl.java:720)
                                                                       at com.paypal.merchant.sdk.internal.TransactionManagerImpl.processPayment(TransactionManagerImpl.java:685)
                                                                       at com.paypal.merchant.sdk.internal.ui.SDKUITransactionController.processPaymentInternal(SDKUITransactionController.java:223)
                                                                       at com.paypal.merchant.sdk.internal.ui.SDKUITransactionController.processPayment(SDKUITransactionController.java:217)
                                                                       at com.paypal.merchant.sdk.internal.ui.emv.EMVUITransactionController.processPayment(EMVUITransactionController.java:273)
                                                                       at com.paypal.merchant.sdk.internal.ui.emv.EMVUITransactionController.onSuccessfulCardRead(EMVUITransactionController.java:939)
                                                                       at com.paypal.merchant.sdk.internal.ui.emv.EMVUITransactionController$18.onSuccessfulCardRead(EMVUITransactionController.java:812)
                                                                       at com.paypal.merchant.sdk.internal.CardReaderEventSession.onCardReadSuccess(CardReaderEventSession.java:35)
                                                                       at com.paypal.merchant.sdk.internal.CardReaderManagerImpl$CardReadSuccessMessage.run(CardReaderManagerImpl.java:1097)
                                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:158)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                       at 
`

Can you tell me what is wrong?

Thank you

**Comment by ppmtscory** [comment]
@mariannegru this is due to not populating the address correctly in the payment request.  Mainly this has to do with the scopes you request initially in the onboarding not having Address included.  Since there was no permission to get the address of the merchant account, the SDK was not able to get the relevant information to populate the merchant object on the invoice for the payment.  Please make sure you are passing the required scopes as outlined on page 17 of the [Merchant Onboarding Guide](https://github.com/PayPal-Mobile/android-here-sdk-dist/blob/master/docs/Merchant%20Onboarding%20Guide.pdf).  If, after passing all the scopes, you get an invalid scope error in your onboarding flow; you'll need to go into your REST app on developer portal and make sure you have all those scopes selected to be used.

**Comment by ppmtscory** [comment]
Closing per external conversation.
