### ISSUE TITLE
Payment process

### ISSUE THREAD

**Issue by mariannegru** [PayPal-Mobile/android-here-sdk-dist#57]
Hi,

Having this code for starting a payment:

`BigDecimal a = new BigDecimal(amount/ 100.0f);
        if(!PayPalHereSDK.getTransactionManager().hasActiveTransaction()) {
            mInvoice = PayPalHereSDK.getTransactionManager().beginPayment(a, this);

            PayPalHereSDK.getTransactionManager().setCardReaderMonitor(true);
            PayPalHereSDK.getTransactionManager().activateReaderForPayment();
        }
        PayPalHereSDK.getTransactionManager().activateReaderForPayment();`

And on public void onUserPaymentOptionSelected(PaymentOption paymentOption) from TransactionController I use PayPalHereSDK.getTransactionManager().processPayment but I get this error:
`                                                                java.lang.NullPointerException: Attempt to invoke interface method 'org.json.JSONObject com.paypal.merchant.sdk.domain.SecureCreditCard.getSecureData()' on a null object reference
                                                                     at com.paypal.merchant.sdk.internal.service.impl.hereapi.HereTakePaymentRequest.getPayloadAsString(HereTakePaymentRequest.java:137)
                                                                     at com.paypal.merchant.sdk.internal.service.PaymentServiceImpl.getCardPaymentPayload(PaymentServiceImpl.java:955)
                                                                     at com.paypal.merchant.sdk.internal.TransactionManagerImpl$InterceptEventMessage.run(TransactionManagerImpl.java:2461)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:158)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)`

Using the PayPalHereSDK.getTransactionManager().processPaymentWithSDKUI works fine but I do not need email receipt screen. Can I have an example of payment without SDK UI?

Thank you

**Comment by ppmtscory** [comment]
The non-UI methods will work fine **without** the EMV reader.  With the EMV reader, you have to use the UI provided which will show the receipt screen.  EMV Certification mandates various UI requirements so this is why the UI methods are required with the EMV reader.

**Comment by mariannegru** [comment]
Ok, thank you for respnse. Is the receip screen mandatory? Is there a way to skip that?

**Comment by ppmtscory** [comment]
Correct, it's required as part of the UI.

**Comment by mariannegru** [comment]
But what if I need to print the receipt on a thermal printer? Is there a way to customise that?

**Comment by mariannegru** [comment]
I found the solution: I need to use SDKReceiptScreenOptions
