### ISSUE TITLE
Payment error

### ISSUE THREAD

**Issue by mariannegru** [PayPal-Mobile/android-here-sdk-dist#60]
Hi

I have this error please using both my app and this sample app:

`04-05 15:39:28.811 25936-25936/com.paypal.heresdk.sampleapp E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: com.paypal.heresdk.sampleapp, PID: 25936
                                                                              java.lang.RuntimeException: Unable to start activity ComponentInfo{com.paypal.heresdk.sampleapp/com.paypal.merchant.sdk.internal.ui.emv.EMVPaymentActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.math.BigDecimal.signum()' on a null object reference
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3253)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349)
                                                                                  at android.app.ActivityThread.access$1100(ActivityThread.java:221)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:158)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                               Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.math.BigDecimal.signum()' on a null object reference
                                                                                  at java.math.BigDecimal.compareTo(BigDecimal.java:2079)
                                                                                  at com.paypal.merchant.sdk.internal.util.MerchantUtil.isAmountTooLow(MerchantUtil.java:119)
                                                                                  at com.paypal.merchant.sdk.internal.ui.SDKUITransactionController.performPreVerificationChecks(SDKUITransactionController.java:115)
                                                                                  at com.paypal.merchant.sdk.internal.ui.emv.EMVUITransactionController.performPreVerificationChecks(EMVUITransactionController.java:192)
                                                                                  at com.paypal.merchant.sdk.internal.ui.emv.EMVPaymentActivity.onCreate(EMVPaymentActivity.java:27)
                                                                                  at android.app.Activity.performCreate(Activity.java:6876)
                                                                                  at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                                                  at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3206)
                                                                                  at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3349) 
                                                                                  at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:158) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
04-05 15:39:28.811 25936-25991/com.paypal.heresdk.sampleapp I/System.out: (HTTPLog)-Static: isSBSettingEnabled false`

**Comment by ppmtscory** [comment]
@mariannegru I'll keep this issue open while we work through your account setup via email and you are able to test out a payment.

**Comment by ppmtscory** [comment]
Closing per external conversations.
