### ISSUE TITLE
software update failed

### ISSUE THREAD

**Issue by brooth** [PayPal-Mobile/android-here-sdk-dist#72]
Hi, I try to implement paypal payments within my app. I installed your sample app and after I connect to my reader (sandbox credentials) it's starting the update process but It always fails at step 6. In logcat I can see next errors:

```
E: [1626] BasicNetwork.performRequest: Unexpected response code 500 for https://www.sandbox.paypal.com/webapps/hereapi/merchant/v1/cardReaderDevice/MIURA/M000/keys
E: HereDeviceKeysRequest- RESPONSE BODY ON ERROR: {"correlationId":"bb4a0664c2b77","errorCode":600000,"message":"MobileMerchantPaymentServ: Unknown Error Code: 506713","errorType":"service_error"}
```

```
E: HereDeviceKeysRequest-Failure response from backend and contains errors. ErrorCode: 600000
```

```
E: SoftwareUpdate: sherlock.paypal.test@haulmont.com : invoke of exchangeEncryptionKeys failed. Calling resetUpdater and failing update process
```

```
E: SoftwareUpdate: sherlock.paypal.test@haulmont.com : onUpdate Failed notifying the listener that update has been failed
E: CardReaderManagerImpl SW_UPDATE-onInstallFailed!!!
```

also warning:

```
W: java.lang.ArrayIndexOutOfBoundsException: src.length=12 srcPos=0 dst.length=1440 dstPos=1440 length=12
W:     at java.lang.System.arraycopy(Native Method)
W:     at com.paypal.merchant.sdk.readers.chipnpin.MiuraSupport.Bond.readP2PEFileResponseReceived(Bond.java:717)
W:     at com.paypal.merchant.sdk.readers.chipnpin.MiuraSupport.Bond.parseResponse(Bond.java:1704)
W:     at com.paypal.merchant.sdk.readers.chipnpin.MiuraSupport.BluetoothServiceListenerImpl.responseReceived(BluetoothServiceListenerImpl.java:49)
W:     at com.paypal.merchant.sdk.readers.chipnpin.MiuraSupport.BluetoothService$ConnectedThread.run(BluetoothService.java:420)
```

**Comment by ppmtscory** [comment]
@brooth the software update only works in the Production environment.  You'll need to either do Production creds with the sample app or you'll need to login to the PayPal Here App with your Live login and the software update will take place there when the reader is connected.

**Comment by ppmtscory** [comment]
Closing this out but please let us know if you run into any issues with the software update in Production.

**Comment by brooth** [comment]
So far I can't login with my own credentials. Here is the error dialog: https://gyazo.com/944a8f96c11d5e077687d9b44b9b7b8c

In logcat:
```
D: onLoginButtonClicked looks like we have live token. Starting payment options activity
D: startPaymentOptionsActivity serverName: Live
D: PPHSDK-We're already initialized hence, ignoring this.
V: CardReaderManagerImpl-registerCardReaderConnnectionListener
D: PayPalHereSDK-setCredentialsFromCompositeStrFromMidTierServer composteStr: sdk_token=live:<removed>
D: AllServers-setServerToUseGivenServiceName setting the hostEntry: Live=https://www.paypal.com
D: PayPalHereSDK-Successfully got the credentials from composite str
D: MerchantStatusRequest-
   Request URL: https://www.paypal.com/webapps/hereapi/merchant/v1/status
   Type: GET
   Payload:
   null
   Headers:
   {
     X-PAYPAL-REQUEST-SOURCE = MPA-DEVICE_Android_LGE-Nexus 4_22_SDK_1.6.2.6_com.paypal.heresdk.sampleapp_1.0-L0
     Authorization = [-REDACTED-]
   
   }
D: MerchantStatusRequest- Response Body: 
   {
       "status": "ineligible",
       "businessCategoryExists": false
   }
D: MerchantStatusRequest-Successful response from backend
D: CalLoggingService-NEW MESSAGE: {"status":"0","type":"BIZ","name":"MerchantStatusRequest.CLIENT","data":{"sessionId":"<removed>","timestamp":"2016-06-24 01:04:14:663 +0000","actionId":"MerchantStatusRequest","level":"TRACE","result":"0","duration":571}}
D: initializeSDK setCredentialsFromCompositeStr onError error: com.paypal.merchant.sdk.domain.PPError@120aa241
D: PayPalHere SDK initialize onErrorWhileSettingAccessTokenToSDK
```
I tried to clear data and reinstall the app but still getting this error.
I also not allowed to install PayPal Here App due to it's not available in Russia.

**Comment by brooth** [comment]
We've just created UK merchant account and faced another issue with it. The dialog the same but in logcat  another response:

```
06-24 09:01:09.495 D: Starting LogRiskMetadataTask
06-24 09:01:09.689 D: com.paypal.merchant.sdk.internal.service.SDKServiceImpl$FeatureMapRequest- Response Body: 
                      {
                          "VERSION": "1.1",
                          "GLOBAL": {
                              "sig": false,
                              "apic": true,
                              "nslall": false,
                              "fhlem": [],
                              "fhlbid": [],
                              "SWU_CHECK_PERIOD": 300,
                              "READER_SLEEP_DELAY": 60
                          },
                          "ANDROID": {
                              "minSDKVersion": "1.0"
                          },
                          "IOS": {
                              "minSDKVersion": "1.0"
                          },
                          "US": {
                              "MCC_CODES": {
                                  "4121": "*",
                                  "5812": "*",
                                  "5813": "*",
                                  "5814": "*",
                                  "7230": "*",
                                  "7298": "*",
                                  "4411": "*",
                                  "7519": "*",
                                  "7011": "*",
                                  "7512": "*"
                              },
                              "CONTACTLESS_LIMIT": "10000"
                          },
                          "GB": {
                              "CONTACTLESS_LIMIT": "30"
                          },
                          "AU": {
                              "CONTACTLESS_LIMIT": "*"
                          }
                      }
06-24 09:01:10.107 D: MerchantStatusRequest- Response Body: 
                      {
                          "status": "ineligible",
                          "categoryCode": "7375",
                          "businessCategoryExists": true
                      }
06-24 09:01:10.108 D: MerchantStatusRequest-Successful response from backend
06-24 09:01:10.109 D: CalLoggingService-NEW MESSAGE: {"status":"0","type":"BIZ","name":"MerchantStatusRequest.CLIENT","data":{"sessionId":"<removed>","timestamp":"2016-06-24 09:01:10:108 +0000","actionId":"MerchantStatusRequest","level":"TRACE","result":"0","duration":1708}}
06-24 09:01:10.113 D: initializeSDK setCredentialsFromCompositeStr onError error: com.paypal.merchant.sdk.domain.PPError@33d66ba8
06-24 09:01:10.113 D: PayPalHere SDK initialize onErrorWhileSettingAccessTokenToSDK
```

**Comment by ppmtscory** [comment]
It appears that you don't have PayPal Here enabled on the account.  This would be the reason you see the `"status": "ineligible"` response.  You'll need to apply for PayPal Here for that account via https://www.paypal.com/webapps/mpp/credit-card-reader.

**Comment by brooth** [comment]
Ok, after all it works. The reader was updated with no errors. Thanks!
